//If- Else condition
Object Demo
{
    def main(args: Array[string]):Unit =
    {
        var x: Int =  30
        if(x<30)
        {
            println("This is if statement")
        }
        else
        {
            println("This is sa else stament")
        }
    }
}

// Else =IF condition
Object ElseIf
{
    def main(args: Array[string]):Unit =
    {
        var x: Int =  30
        if(x ==20)
        {
            println("This is if statement")
        }
        else if(x == 20)
        {
            println("This is if-else stament")
        }
        else if(x == 23)
        {
            println("This is 30")
        }
        else {
            println("This is If-Else Demo")
        }
    }
}